version: '3'
services:
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  web:
    image: hoyai/tf_edu_docker_skp:v0.8
    env_file: .env
    volumes:
      - ./code:/code
      - ./code/static:/static
    ports:
     - "8888:8888"
     - "8989:8989"
     - "5555:5555"
    command: bash -c "(gunicorn tfrest.wsgi -b 0.0.0.0:8000 &)&&(flower -A tfrest &)&&/run_jupyter.sh;"
    #command: bash -c "(python manage.py runserver 0.0.0.0:8000 &)&&/run_jupyter.sh;"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./code:/code
      - ./config/nginx:/etc/nginx/conf.d
      - ./code/static:/static
    depends_on:
      - web
    env_file: .env
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    depends_on:
      - web
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin
  celery:
    image: hoyai/tf_edu_docker_skp:v0.8
    volumes:
      - ./code:/code
    command: bash -c "/run_celery.sh;"
    depends_on:
      - rabbit

volumes:
    pg_data:
     external: true
